{
 "title": "Suricata Dashboard",
 "tags": [
  "Suricata",
  "Loki",
  "IDS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "src_ip", "label": "Source IP", "query": "label_values(src_ip)" }
  ]
 },
 "panels": [
  {
   "title": "Proto",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"suricata\"} \n| json\n| line_format \"{{.proto}}:{{.app_proto}} ({{.dest_port}})\""
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"suricata\"} \n| json \n| src_ip!~\".*:.*\" \n| dest_ip!~\".*:.*\" \n| line_format \"{{.src_ip}}:{{.src_port}} -> {{.dest_ip}}:{{.dest_port}}\""
    }
   ]
  },
  {
   "title": "Destination IPv4 by time",
   "type": "logs",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"suricata\"} | json | dest_ip!~\".*:.*\" | line_format \"{{.dest_ip}}:{{.dest_port}}\""
    }
   ]
  }
 ]
}