%YAML 1.1
---
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /suricata_logs/eve.json
      types:
        - alert
        - dns
        - http
        - tls
        - flow